project_name: helmdocs

builds:
  - id: binary
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    main: ./cmd/cmd.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "danspts/helmdocs:{{ .Version }}"
    dockerfile: Dockerfile


archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"
