name: Release

on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Run tests with coverage
      run: |
        go test -v ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out
  release-please:
    if: github.ref == 'refs/heads/main'
    needs: [test, golangci]
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }} 
      version: ${{ steps.release-please.outputs.version }}
      all: ${{ toJSON(steps.release-please.outputs) }}
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    permissions:
      contents: write
      packages: write
      attestations: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: git fetch --force --tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
